language: android
jdk: oraclejdk7

env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=2048m"

before_install:
 - git fetch --tags

install:
  - ./ops/sdk.sh

script:
 - ./gradlew build assemble test --stacktrace -PdisablePreDex

after_success:
 - ./gradlew artifactoryPublish

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $ANDROID_HOME/build-tools/
    - $ANDROID_HOME/tools/
    - $ANDROID_HOME/platform-tools/
    - $ANDROID_HOME/platforms/android-23/
    - $ANDROID_HOME/extras/

notifications:
  email: change