language: android
jdk: oraclejdk7

android:
  components:
  - android-21
  - build-tools-21.1.2

before_install:
 - git fetch --tags

script:
 - ./gradlew clean build assemble --stacktrace

after_success:
 - ./gradlew artifactoryPublish

notifications:
  email: change