language: android
jdk: oraclejdk7

android:
  components:
  - platform-tools
  - tools
  - android-23
  - build-tools-23.0.2
  - extra-android-support
  - extra-android-m2repository

env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=2048m"

before_install:
 - git fetch --tags

script:
 - ./gradlew build assemble test --stacktrace -PdisablePreDex

after_success:
 - ./gradlew artifactoryPublish

notifications:
  email: change