language: android
jdk: oraclejdk7

android:
  components:
  - android-22
  - build-tools-22.0.1
  - extra-android-support
  - extra-android-m2repository

before_install:
 - git fetch --tags

script:
 - ./gradlew clean build assemble --stacktrace

after_success:
 - ./gradlew artifactoryPublish

notifications:
  email: change